# Generated by Django 4.2.30 on 2026-07-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16)),
                ('reference', models.TextField()),
                ('pointer', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['type', 'source_id'],
            },
        ),
        migrations.CreateModel(
            name='ValidationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ruleset', models.CharField(max_length=16)),
                ('heirs', models.JSONField()),
                ('expected', models.JSONField()),
                ('aul_base', models.IntegerField(blank=True, null=True)),
                ('radd', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ruleset', 'name'],
            },
        ),
    ]
